configfile: "config.yaml"

rule index:
  input:
    "sidebar.notes", "TODO.notes"
  output:
    "README.md",
    "wiki/sidebar.txt"
  shell:
    '''
    cat <(sed 's/\*\*//g' {input[0]}) {input[1]} > /tmp/{input[0]};
    {config[md]} /tmp/{input[0]} -o {output[0]};
    sed 's/\.\./\./g' {input[0]} > /tmp/{input[0]};
    {config[wk]} /tmp/{input[0]} -o {output[1]} --compact_toc
    '''

rule installation:
  input:
    "installation.notes"
  output:
    "../src/README.md",
    "wiki/src.txt"
  shell:
    '''
    {config[md]} {input[0]} -o {output[0]};
    {config[wk]} {input[0]} -o {output[1]} --compact_toc
    '''

rule vignettes_one_sample:
  input:
    "vignettes-one-sample.notes"
  output:
    "../vignettes/one_sample_location/README.md",
    "wiki/vignettes/one-sample-location.txt"
  shell:
    '''
    {config[md]} {input[0]} -o {output[0]};
    {config[wk]} {input[0]} -o {output[1]} --compact_toc
    '''

rule all:
  input:
    rules.index.output, rules.installation.output,
    rules.vignettes_one_sample.output
