__doc__ = 'Installation script for dsc2'
__author__ = "Gao Wang"
__copyright__ = "Copyright 2016, Stephens lab"
__email__ = "gaow@uchicago.edu"
__license__ = "MIT"

rule help:
  shell: "snakemake -l"

rule pysos:
  shell: "svn checkout https://github.com/gaow/SOS/trunk/pysos"

rule install:
  output:
    touch("build.done")
  shell: "python setup.py install"

rule test:
  shell: "echo TODO ..."

rule clean:
  shell: "rm -rf build.done dist *.egg-info"

rule purge:
  shell: "git clean -df"

rule all:
  input:
    "build.done"
  shell: "snakemake clean"
