---
title: "My Simulation"
author: "My Name"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
---

```{r setup, include=FALSE}
library(knitr)
code <- c("model_functions.R",
          "method_functions.R",
          "eval_functions.R",
          "main.R")
code_lastmodified <- max(file.info(code)$mtime)
sapply(code, read_chunk)
```

This is a `knitr` report generated by the `simulator` to describe your simulation.
Knitting this file will rerun the simulation if any of the code files have been
modified since the `simulation` object was last created.

# Main simulation

```{r}
library(simulator)
```

```{r, echo = FALSE, results = 'hide', warning = FALSE, message = FALSE}
<<models>>
<<methods>>
<<metrics>>
```

```{r, eval = FALSE}
<<init>>
<<main>>
```

```{r, echo = FALSE, results = 'hide', message = FALSE, warning = FALSE}
<<init>>
sim_lastmodified <- file.info(sprintf("files/sim-%s.Rdata",
                              name_of_simulation))$mtime
if (is.na(sim_lastmodified) || code_lastmodified > sim_lastmodified) {
  <<main>>
} else{
  sim <- load_simulation(name_of_simulation)
}
```

We can make plots.

```{r, fig.width = 6, fig.height = 4, results = 'hide', warning = FALSE, message = FALSE}
<<plots>>
```

And tables too.

```{r, results = 'asis'}
<<tables>>
```

# Components

## Models

```{r, eval = FALSE}
<<models>>
```

## Methods

```{r, eval = FALSE}
<<methods>>
```

## Metrics

```{r, eval = FALSE}
<<metrics>>
```


# Conclusion

To cite the `simulator`, please use

```{r, results='asis'}
citation("simulator")
```
